name: pandora
version: 1.0.0+1
publish_to: none
description: 用来学习Flutter的项目框架采用getx，api接口来自互联网如果发现违规数据请自己切换接口仅仅只做演示使用。
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  webview_flutter: ^4.2.2
  quick_actions: ^1.0.5
  fl_video: ^1.2.3
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  animated_notch_bottom_bar: ^1.0.0
  markdown_widget: ^2.2.0
  extended_image: ^8.0.2
  html2md: ^1.3.0
  flutter_easyrefresh_strong: ^2.2.1
  animation_search_bar: ^0.0.10
#  ext_video_player: ^0.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons_maker: ^0.10.2
flutter_icons: {android: launcher_icon, image_path: assets/icon/icon.png, ios: true,
                flutter_lints: ^1.0.4 }
flutter: 
  uses-material-design: true

